import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faBars,
  faPowerOff,
  faBell,
  faExclamationCircle,
  faArrowAltCircleRight,
  faUserAlt,
  faAtom,
  faThLarge,
  faOutdent,
  faSignOutAlt,
  faEllipsisV,
  faChevronUp,
  faIndent,
  faSchool,
  faBuilding,
  faTrash,
  faPencilAlt,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleDoubleRight,
  faAngleRight,
  faWindowClose,
  faSave,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faBars,
  faPowerOff,
  faBell,
  faExclamationCircle,
  faArrowAltCircleRight,
  faUserAlt,
  faAtom,
  faThLarge,
  faOutdent,
  faSignOutAlt,
  faEllipsisV,
  faChevronUp,
  faIndent,
  faSchool,
  faBuilding,
  faTrash,
  faPencilAlt,
  faAngleDoubleLeft,
  faAngleLeft,
  faAngleDoubleRight,
  faAngleRight,
  faWindowClose,
  faSave
);

export default library;
