export const api = '/api/v1';

//auth
export const auth = {
  LOGIN: 'LOGIN',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGIN_ERROR: 'LOGIN_ERROR',
  LOGIN_FAILED: 'LOGIN_FAILED',
};

export const profesi = {
  FETCHING_DATA_PROFESI: 'FETCHING_DATA_PROFESI',
  GET_ALL_PROFESI: 'GET_ALL_PROFESI',
  GET_BY_ID_PROFESI: 'GET_BY_ID_PROFESI',
  POST_PROFESI: 'POST_PROFESI',
  UPDATE_PROFESI: 'UPDATE_PROFESI',
  DELETE_PROFESI: 'DELETE_PROFESI',
};

export const pendidikan = {
  FETCHING_DATA_PENDIDIKAN: 'FETCHING_DATA_PENDIDIKAN',
  GET_ALL_PENDIDIKAN: 'GET_ALL_PENDIDIKAN',
  GET_BY_ID_PENDIDIKAN: 'GET_BY_ID_PENDIDIKAN',
  POST_PENDIDIKAN: 'POST_PENDIDIKAN',
  UPDATE_PENDIDIKAN: 'UPDATE_PENDIDIKAN',
  DELETE_PENDIDIKAN: 'DELETE_PENDIDIKAN',
};

export const user = {
  FETCHING_DATA_USER: 'FETCHING_DATA_USER',
  GET_ALL_USER: 'GET_ALL_USER',
  GET_BY_ID_USER: 'GET_BY_ID_USER',
  POST_USER: 'POST_USER',
  UPDATE_USER: 'UPDATE_USER',
  DELETE_USER: 'DELETE_USER',
};
